Experiments/Experiment_4/contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:people_id>/', views.detail, name='detail'),
    path('search', views.search, name='search'),
]

Experiments/Experiment_4/contact/models.py
from django.db import models

# Create your models here.


class People(models.Model):
    name_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.name_text


class Phone(models.Model):
    People = models.ForeignKey(People, on_delete=models.CASCADE)
    number = models.CharField(max_length=200)

    def __str__(self):
        return self.number


class Address(models.Model):
    People = models.ForeignKey(People, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.address

Experiments/Experiment_4/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import People
from django.http import Http404
from django.views.decorators import csrf


# Create your views here.


def index(request):
    people_list = People.objects.order_by('-pub_date')[:5]
    template = loader.get_template('contact/index.html')
    context = {
        'people_list': people_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, people_id):
    try:
        people = People.objects.get(pk=people_id)
    except People.DoesNotExist:
        raise Http404('该人不在通讯录')
    return render(request, 'contact/detail.html', {'people': people})


def search(request):
    ctx = {}

    if request.POST:
        ctx['rlt'] = request.POST['q']
        name = request.POST['q']
        print(request.POST['q'])
        try:
            people = People.objects.get(name_text=name)
        except:
            raise Http404("该人不在通讯录")

    return render(request, 'contact/detail.html', {'people': people})

Experiments/Experiment_4/contact/templates/contact/detail.html
<h2>name</h2>
<p>{{ people.name_text }}</p>

<h2>number</h2>
{% for number in people.phone_set.all %}
<p>{{number}}</p>
{% endfor %}

<h2>address</h2>
{% for address in people.address_set.all %}
<p>{{address}}</p>
{% endfor %}

Experiments/Experiment_4/contact/templates/contact/index.html
<h1>通讯录</h1>
<form action="/contact/search"method="post">
{% csrf_token %}
<input type="text" name="q">
<input type="submit" value="search">
</form>
{% if people_list %}
    <ul>
    {% for people in people_list %}
        <p>name</p><li><a href="/contact/{{people.id}}/">{{people.name_text}}</a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>查无此人</p>
{% endif %}

Experiments/Experiment_4/contact/templates/contact/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search</title>
</head>
<body>
    <form action="/search-post", method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value="Submit">
    </form>

    <p>{{ rlt }}</p>
</body>
</html>